[build]
  functions = "netlify/functions"
  publish = "."

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

  [functions."coach_smart_rocks"]
    timeout = 26